apiVersion: v1
kind: Service 
metadata:
  name: demo-java-service
spec:  
  selector:
    app: demo-java
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 8080 # Container Port