apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: registry.gitlab.com/betejb/springboot-demo/go-app:v1
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
          name: http-port
        env:
          - name: REDIS_URL
            value: redis-go.go-app.svc
        resources:
          limits:
            cpu: '100m'
            memory: 100Mi
          requests:
              cpu: '100m'
              memory: 50Mi
      imagePullSecrets:
      - name: regcred