apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: go-app
  labels:
    app: go-app
spec:
  ports:
  - port: 8080
    name: http-port
  clusterIP: None
  selector:
    app: go-app
  type: ClusterIP